### PR TITLE
Add rss-listing and link in help page

### PR DESCRIPTION
**Pull request by pedro-psb**
This adds @himdel [rss feed link](https://himdel.eu/feed/pulp-changes.json) into pulp website and a simple listing of it's content.

Its added to the end of the help page (after quicklinks).

image

### CODE REVIEW

**Comment by pedro-psb** [comment]
I tried creating an html page `/rss/index.html` with ` <link rel="alternate" type="application/rss+xml" title="Changes RSS Feed" href="https://himdel.eu/feed/pulp-changes.json" />` in the head tag, but the rss client I tried wasnt able to fetch from that link (only directly from your server).

But I guess it's okay to keep your server link, if you don't mind.
Later I can create a similar script in python to generate the rss-json on build time (it's built/published nightly).

**Comment by himdel** [comment]
:+1: 

Yeah, most rss readers expect to get urls directly to the feed, the `<link` is just so that browsers/extensions can tell you about the feed being there and send it to the reader.

I'm fine with using my server, it's just serving a static file, and reparsing the changlogs daily :)

Thanks for adding this :)

**Comment by pedro-psb** [comment]
> Yeah, most rss readers expect to get urls directly to the feed, the <link is just so that browsers/extensions can tell you about the feed being there and send it to the reader.

Oh, I didnt know exactly how that worked. So it is supposed to be on all pages' headers, right? I could do that.
But isnt the `type="application/rss+json"`, instead of `type="application/rss+xml"`?

**Comment by himdel** [comment]
Ah, yeah, it should be everywhere if we want that part to work :) (To be fair the last time majority of browsers supported this was like 2012, but I believe Opera still does, and there's extensions for the other browsers, such as https://chromewebstore.google.com/detail/rss-subscription-extensio/nlbjncdgjeocebhnmkbbbdekmmmcbfjd )

> But isnt the type="application/rss+json", instead of type="application/rss+xml"?

Yeah, that's a valid point. I only ever saw rss+xml and atom+xml for rss/atom in the wild, but according to https://www.jsonfeed.org/, the correct mime-type is `application/feed+json`.

**Pull request merged**
